image: node:16.13

stages:
  - test
  - pre-deploy
  - deploy

Lint / Code format:
  stage: test
  script:
    - npm i
    - npx hardhat compile
    - npm run lint
    - npm run prettier
    - npm test --coverage
    - npm run typescript
    - npm run solhint
  coverage: /All files\s*\|\s*([\d\.]+)/

Migrate DEV database:
  stage: pre-deploy
  except:
    - main
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
    - apt-get install -y nodejs
    - npm i
    - npm run db-migrate:down

Rollback DEV database:
  stage: pre-deploy
  when: manual
  except:
    - main
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
    - apt-get install -y nodejs
    - npm i
    - npm run db-migrate:up

# Deploy to production:
# stage: deploy
# image: node:16-alpine
# when: manual
# only:
#   - main
# script:
#   - apk add git
#   - npm i --location=global vercel
#   - VERCEL_ORG_ID=$VERCEL_ORG_ID VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID vercel --confirm -t $VERCEL_TOKEN --prod
