image: node:16.13

Lint / Code format:
  stage: deploy
  script:
    - npm i
    - npx hardhat compile
    - npm run lint
    - npm run prettier
    - npm test --coverage
    - npm run typescript
    - npm run solhint
  coverage: /All files\s*\|\s*([\d\.]+)/
