version: "3"
services:
  mysql:
    platform: linux/x86_64 # Needed for Apple M1
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: indivisible
      MYSQL_ROOT_PASSWORD: root_pwd
    volumes:
      - ./data/mysql:/var/lib/mysql
